DROP ROLE IF EXISTS live_docs_data;
CREATE ROLE live_docs_data LOGIN ENCRYPTED PASSWORD 'md5b4b9b7572dbcb85b74183ef0d9005527'
  SUPERUSER CREATEDB CREATEROLE REPLICATION
   VALID UNTIL 'infinity';

DROP DATABASE IF EXISTS live_docs_data;
CREATE DATABASE live_docs_data
  WITH ENCODING='UTF8'
       OWNER=live_docs_data
       CONNECTION LIMIT=-1;
